# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('event_type', models.CharField(max_length=30, verbose_name='event_type')),
                ('repository', models.CharField(max_length=70, verbose_name='repository')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='GitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='EMail')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('admin', models.CharField(max_length=50, verbose_name='admin')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('git_users', models.ManyToManyField(to='core.GitUser')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='gitUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GitUser'),
        ),
    ]
