# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='git_users',
            field=models.ManyToManyField(blank=True, null=True, to='core.GitUser'),
        ),
    ]
