# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20160712_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gituser',
            name='user',
        ),
        migrations.AddField(
            model_name='gituser',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
